<?php
session_start();
error_reporting(0);

use Razorpay\Api\Api;

require "vendor/autoload.php";
$keyId = 'rzp_test_w6piYgRbvr2gD1';
$keySecret = '0BCuZqTRBmwyaruKUkipjXoY';
$api = new Api($key_id, $secret);
$receipt = time() . rand(0, 10000000);
$order = $api->order->create(array('receipt' => $receipt, 'amount' => 100, 'currency' => 'INR'));
$order_id = $order['id'];
$order_receipt = $order['receipt'];
$order_amount = $order['amount'];
$order_currency = $order['currency'];
$order_created_at = $order['created_at'];
$_SESSION['razorpay_order_id'] = $order_id;

?>
<!DOCTYPE html>
<html lang="en">

<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>PAGE</title>
</head>

<body>
<form action="success.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="0BCuZqTRBmwyaruKUkipjXoY" //
    data-amount="29935" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="order_CgmcjRh9ti2lP7"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Acme Corp"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="Gaurav Kumar"
    data-prefill.email="gaurav.kumar@example.com"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
</body>

</html>